version: '3'
services:
  balancer:
    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80